//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestModel
    {
        public int Id { get; set; }
        public string Sender { get; set; }
        public string Recipient { get; set; }
        public System.DateTime SendDate { get; set; }
        public string Title { get; set; }
        public string Context { get; set; }
        public int SenderId { get; set; }
        public int RecipientId { get; set; }
        public bool follow { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> Status { get; set; }
        public string IsNew { get; set; }
        public Nullable<bool> IsFollowNew { get; set; }
    }
}
