//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestModel
    {
        public RequestModel()
        {
            this.Follow = false;
            this.IsNew = false;
            this.IsAnswered = false;
        }
    
        public int Id { get; set; }
        public string Sender { get; set; }
        public string Recipient { get; set; }
        public System.DateTime SendDate { get; set; }
        public string Title { get; set; }
        public string Context { get; set; }
        public int SenderId { get; set; }
        public int RecipientId { get; set; }
        public bool Follow { get; set; }
        public string Answer { get; set; }
        public float Status { get; set; }
        public bool IsNew { get; set; }
        public bool IsAnswered { get; set; }
    }
}
